version: '3.3'
services:
  app:
    container_name: FileService
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/baadmin1/file:/app/logs
    #restart: always